project_name: krew-plugin-one
release:
  github:
    owner: gtfisher
    name: krew-plugin-one
builds:
  - id: krew-plugin-one
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/gtfisher/krew-plugin-one/pkg/version.version=
archives:
  - id: krew-plugin-one
    builds:
    - krew-plugin-one
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
