apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: krew-plugin-one
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/gtfisher/krew-plugin-one/releases/download/v0.1.0/krew-plugin-one_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./krew-plugin-one"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-one"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/gtfisher/krew-plugin-one/releases/download/v0.1.0/krew-plugin-one_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./krew-plugin-one"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-one"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/gtfisher/krew-plugin-one/releases/download/v0.1.0/krew-plugin-one_windows_amd64.zip
    sha256: ""
    files:
    - from: "/krew-plugin-one.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-one.exe"
  shortDescription: A new plugin
  homepage: https://github.com/gtfisher/krew-plugin-one
  caveats: |
    Usage:
      $ kubectl krew-plugin-one

    For additional options:
      $ kubectl krew-plugin-one --help
      or https://github.com/gtfisher/krew-plugin-one/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
